### ISSUE TITLE
It's assumed that FormattedMessage is used and it shouldn't

### ISSUE THREAD

**Issue by juancaacuna** [gtournie/redux-form-validators#1]
When evaluating (with Redux Form's "validate" function approach), the returned object is always a FormattedMessage.

Expected result: If 'message' is not explicitly a FormattedMessage, then a regular string should be returned with the message.

**Comment by gtournie** [comment]
@juancaacuna: Are you suggesting to drop the react-intl dependency? If not, it's already the default behavior, as mentioned in the doc:

https://github.com/gtournie/redux-form-validators#message-alias-msg
> This will be wrapped in a FormattedMessage (with the message as id), will look for a message with this id and **will finally fallback to the id**.

**Comment by juancaacuna** [comment]
No, not to drop it. The weird behavior is that I'm not using FormattedMessage, however, the returned object after evaluating, is a FormattedMessage (as if this one if the default).

Specifically in this part:
errors[field] = validations[field].find(validateField => validateField(value))

**Comment by gtournie** [comment]
I added a general validation example:
https://github.com/gtournie/redux-form-validators/blob/master/examples/src/general-validation-form.js#L56-L70

And I tried to pass a regular string as a msg. As a result, it worked.

Did I missed something? Could you give me a snippet?

**Comment by juancaacuna** [comment]
I found something. The instructions in npm are a little bit different. Another thing is that I'm using immutable.js.

`errors[field] = validations[field].map(validateField => validateField(value)).find(x => x)`
vs
`errors[field] = validations[field].find(validateField => validateField(value))`
 
https://www.npmjs.com/package/redux-form-validators

**Comment by gtournie** [comment]
There was an issue in the docs, indeed. Is everything ok now?

**Comment by juancaacuna** [comment]
Yeah all good! Thanks! :)
