### ISSUE TITLE
url({allowBlank: true}) does't work

### ISSUE THREAD

**Issue by StanZhuravlev** [gtournie/redux-form-validators#11]
Hi!

I begin use a redux-form-validators, but have issue: I make:

`<Field ....... validate={url({allowBlank: true})}`

I think, that if my Field is empty, error will not show. But I see error on empty (blank) field after load form. 

I review a source of [url.js](https://github.com/gtournie/redux-form-validators/blob/master/src/url.js), but not see a allowBlank processing. :( 

How best way use url validator for field level validation?

**Comment by gtournie** [comment]
@StanZhuravlev I don't know how to see your error (the allowBlank option is processed in the prepare function - url uses regFormat, which uses prepare).
I just added an url example. You can check it out by running `npm run start` from the project's root directory (just ensure to do a `git pull` first). You can also check the code here: [examples/src/field-validation-form.js](https://github.com/gtournie/redux-form-validators/blob/master/examples/src/field-validation-form.js).
If you still have an error, please create a snippet and to put the link here (or tell me how I can reproduce the bug). I'll reopen this ticket then.

**Comment by StanZhuravlev** [comment]
Hi!

I can't make a snippet. I use [https://npmcdn.com/redux-form-validators@2.0.2/lib/index.js](https://npmcdn.com/redux-form-validators@2.0.2/lib/index.js), but have error: "Uncaught ReferenceError: exports is not defined at VM1325 index.js:3". Do you have another cdn-based library?

**Comment by gtournie** [comment]
@StanZhuravlev you need to configure your snippet to support es6 and react. You should probably start by finding a very simple snippet already configured. Or you can use another snippet editor (I would recommend https://codesandbox.io/ which is pretty easy to use)
