### ISSUE TITLE
How to use tooLong and tooShort messages in length validator

### ISSUE THREAD

**Issue by dszymczuk** [gtournie/redux-form-validators#12]
Hi

I'm not sure how to use validation messsages with length. When I make something like this:

```javascript
<Field
  id="title"
  type="text"
  name="title"
  placeholder="Ener title"
  component={Input}
  label="Title"
  helpText="Min 5, max 70"
  validate={[required({message: 'Required'}), length({
    min: 5,
    max: 70,
    messages: {
      tooShort:"Title is too short",
      tooLong:"Title is too long"
    }
  })]}
/>
```

I can see only default message. I've tried with msg, massage but it doesn't work.
How can I apply tooShort and tooLong messages ?

**Comment by gtournie** [comment]
@dszymczuk: https://github.com/gtournie/redux-form-validators#message-alias-msg
The message option let you redefine only one message, so you need to add 2 validators:
`length({ min: 5, msg: "Title is too short" }), length({ max: 70, msg: "Title is too long" })`

That could be a nice feature tho, I'll think about it.

**Comment by gtournie** [comment]
@dszymczuk With version 2.1.0, you can now set `messages` like you did:
```
messages: {
  tooShort: "Title is too short",
  tooLong: "Title is too long"
}
```

**Comment by dszymczuk** [comment]
Thank you ! It will be easier (and more readable) than add two validators.
