### ISSUE TITLE
Default error messages

### ISSUE THREAD

**Issue by nealoke** [gtournie/redux-form-validators#13]
Hi! This looks very sweet as I was copying and pasting a lot of these functions between projects. Just a question is it possible to change the default error messages?

And another question, is there a reason you named all functions without a prefix? In my projects I often have `email` or `url` already assigned and my validators are with a small prefix which makes it a bit clearer to myself like `isEmail` and `isUrl`.

**Comment by gtournie** [comment]
@nealoke: you know you can rename a function when you import it? So the original name doesn't really matter ;) Just do: `import { email as isEmail }  from 'redux-form-validators'` if you want to use `isEmail`.

There is currently 2 ways to change the default error messages:
- using `react-intl` (recommended if you need to translate your messages)
- overriding `Validators.formatMessage`:
```
import Validators from 'redux-validators'

const DEFAULT_ERROR_MESSAGES = {
  presence: "can't be blank",
  ...
}
let originalFormatMessage = Validators.formatMessage
Validators.formatMessage = (msg) => {
  if (msg.id) {
    let type = msg.id.split('.').pop()
    msg.defaultMessage = DEFAULT_ERROR_MESSAGES[type] || msg.defaultMessage
  }
  return originalFormatMessage(msg)
}
```
I'll probably try to make it simpler in a next version.

**Comment by nealoke** [comment]
@gtournie Works like a charm! 😍

**Comment by nealoke** [comment]
@gtournie When does the `msg` param have the `.props` attribute?

**Comment by gtournie** [comment]
@nealoke When it's a FormattedMessage obj (react-intl)
