### ISSUE TITLE
Add support for object validation

### ISSUE THREAD

**Issue by gsantiago** [gtournie/redux-form-validators#14]
Currently, the `prepare` helper method converts all values to string. So, if the `<Field />` pass an object as value, the validator function will receive something like `"[object Object]"`.

This makes harder to validate any type of object, specially `File` objects from `<input type='file' />`.

**Comment by gtournie** [comment]
@gsantiago I'm working on it

**Comment by gtournie** [comment]
@gsantiago I added a file validator in v2.2.0. Also, the prepare function doesn't convert the value into string anymore if it's an object
