### ISSUE TITLE
Add support for custom property on provided validators

### ISSUE THREAD

**Issue by nealoke** [gtournie/redux-form-validators#15]
I was wondering if it is possible to create custom properties such as the following example:

`validate={[isRequired({ intl: false }), isEmail({ intl: false })]}` which would be preferably be able to use in the `formatMessage` function eg:

```
Validators.formatMessage = (msg, props) => {
  if (props.intl) {
    // Stuff
  }

  else {
    // Stuff
  }
}
```

**Comment by gtournie** [comment]
@nealoke: Do you have a specific use case in mind? 

If you want to return a different message for a specific condition, you can just create a new version of the validator with a custom message:

```
import { email } from 'redux-form-validators'

let isEmailIntl = email({ msg: "Custom message" })

... validate={[isEmailIntl()]}
```

**Comment by gtournie** [comment]
@nealoke I close this ticket. Will reopen it if someone give me a relevant use case.
