### ISSUE TITLE
Enforce the use of `Validators.formatMessage` for custom validators

### ISSUE THREAD

**Issue by nealoke** [gtournie/redux-form-validators#16]
I am trying to create a reusable `isBirthday` validator for my different projects. When trying this I've created a `createDefaultReduxErrorMessages` (that naming 🔥 ) to make sure I don't repeat myself setting up default error messages and settings. This is working great for me however when trying to add a custom validator I also want that validator to use the `Validators.formatMessage` (see example at the bottom).

The problem lies in that when I return an object with `id`, `defaultMessage` and `values` from my custom validator it thinks it needs to render the object to the component as the error while totally ignoring my `Validators.formatMessage` function. 

**How do I make custom validators use the `Validators.formatMessage` function is well?** 

**createDefaultReduxErrorMessages**
```
import React from "react";
import Validators from "redux-form-validators";

const originalFormatMessage = Validators.formatMessage;
const defaultMessages = {
  presence: "Required",
  email: "Invalid e-mail adress",
        // Stuff
};

export default function createDefaultReduxErrorMessages(customErrorMessages, FormattedMessage) {
  return (Validators.formatMessage = (msg) => {
    const errorMessages = { ...defaultMessages, customErrorMessages };

    if (msg.id) {
      const type = msg.id.split(".").pop();
      msg.defaultMessage = errorMessages[type] || msg.defaultMessage;

      if (FormattedMessage) {
        return <FormattedMessage {...msg.props || { ...msg, id: `form.${type}` }} />;
      }
    }

    return originalFormatMessage(msg);
  });
}
```

**Example of custom validator**
```
import { addValidator } from "redux-form-validators";

export default addValidator({
  validator: (options, value, allValues) => {
    const onlyNums = value.replace(/[^\d]/g, "");
    const day = onlyNums.slice(0, 2);
    const month = onlyNums.slice(2, 4);
    const year = onlyNums.slice(4, 8);
    const currentYear = new Date().getFullYear();

    if (day > 31 || day === "00") {
      return {
        id: "birthday.day",
        defaultMessage: "Invalid day",
        values: {}
      };
    }
    else if (month > 12 || month === "00") {
      return {
        id: "birthday.month",
        defaultMessage: "Invalid month",
        values: {}
      };
    }
    else if (year > currentYear || year < currentYear - 120) {
      return {
        id: "birthday.year",
        defaultMessage: "Invalid year",
        values: {}
      };
    }
  }
});

```

**Comment by gtournie** [comment]
@nealoke `addValidator` [uses formatMessage internally](https://github.com/gtournie/redux-form-validators/blob/v2.1.0/src/add-validator.js#L18), so the problem doesn't come from there.

Question is: why you're wrapping your code in the createDefaultReduxErrorMessages function?

Also, you know you can use the [date.parseDate](https://github.com/gtournie/redux-form-validators#date-helpers) helper, instead of parsing the date manually?
And you don't need to return a 'values' obj if it's empty.

**Comment by gtournie** [comment]
@nealoke Should be fixed in 2.1.1

**Comment by nealoke** [comment]
@gtournie aah didn't see that it didn't pass :) but good to know that it will be fixed in 2.1.1, do you mind publishing soon? :) 👍

**Comment by nealoke** [comment]
@gtournie I'm wrapping it because I import it back in different projects, so now I can do as shown below. This allows me to only have the dependency on `redux-form-validators` in the `myutilslibrary` and not in every single project I use it ;)

```
import { createDefaultReduxErrorMessages } from "myutilslibrary";
import { FormattedMessage } from "react-intl";

createDefaultReduxErrorMessages({}, FormattedMessage);
```

**Comment by gtournie** [comment]
@nealoke it's already published ;)
