### ISSUE TITLE
Getting error when no return is provided by addValidator

### ISSUE THREAD

**Issue by nealoke** [gtournie/redux-form-validators#18]
I'm using the suggested way to implement default messages as you mentioned #17 and is working great but I currently receive an error when the following custom `validator` does not trigger

```
import { addValidator } from "redux-form-validators";

export default addValidator({
	validator: (options, value, allValues) => {
		if (!/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/i.test(value)) {
			return {
				id: "hexCode",
				values: { hexCode: value }
			};
		}
	}
});
```

When I load the page with the `validator` it triggers the following error `Cannot read property 'id' of undefined` which refers to the function below. This only fires when the `validator` is passing eg returns nothing

```
export default function createDefaultReduxErrorMessages(customErrorMessages, FormattedMessage) {
	return (Validators.formatMessage = (msg) => {
		const errorMessages = { ...defaultMessages, ...customErrorMessages };

		if (msg.id) {
			const type = msg.id.replace("form.errors.", "");
			msg.defaultMessage = _.get(errorMessages, type, undefined) || msg.defaultMessage;

			if (FormattedMessage) {
				return <FormattedMessage {...msg.props || { ...msg, id: `form.${type}` }} />;
			}
		}

		return originalFormatMessage(msg);
	});
}

```

Am I doing something wrong in my custom `validator` or should I just put the `return` statement of the `createDefaultReduxErrorMessages` in the `if (msg.id) {...}`?

**Comment by gtournie** [comment]
@nealoke there is a tiny glitch here. I fixed it in 2.1.2 (I just published it), so it should work now. If you don't want to upgrade to 2.1.2, you can just check msg in formatMessage:
```
  return (Validators.formatMessage = (msg) => {
    const errorMessages = { ...defaultMessages, ...customErrorMessages };
    if (msg && msg.id) {
...
```
