### ISSUE TITLE
Override default messages globally

### ISSUE THREAD

**Issue by ecirish** [gtournie/redux-form-validators#20]
I'm a bit of a react noob, so I apologize if this is obvious. I'm working on a project with lots of redux-forms. So far so good. I wrote some of my own validators in the redux-forms prescribed way. These are better. I'd like to use them, and I can use them, but I'd basically like to be able to override the default messages in one place, add a few validators, and then import and reference them from any given component that contains a redux-form.  Is there an easy way to do this?

**Comment by bogdaniy** [comment]
Hi! I have my own example of overriding default messages
```

**Comment by gtournie** [comment]
@ecirish, @bogdaniy v2.3.0: https://github.com/gtournie/redux-form-validators#default-messages-override

**Comment by ecirish** [comment]
@gtournie Awesome! Thank you.
