### ISSUE TITLE
Support for async validations Like unique email on registeration from server.

### ISSUE THREAD

**Issue by farhantahir** [gtournie/redux-form-validators#22]
I'm using this validators in one my project and in a case for registration form I'm looking for a validation to check if user's entered email is unique or not using a back-end API.

Can we have a validator of this type as well ? 

Thanks

**Comment by nealoke** [comment]
That would be very cool I think 👍

**Comment by gtournie** [comment]
What you're asking is an async field validation. This feature doesn't depend on me: https://github.com/erikras/redux-form/issues/2763
