### ISSUE TITLE
Validation 'confirmation' does not work with general-validation-form

### ISSUE THREAD

**Issue by cloudyster** [gtournie/redux-form-validators#3]
Validation 'confirmation' works fine in _field-validation-form_ but fails if applied in _general-validation-form_ - validation fails with 'doesn't match `Password`'

**Comment by gtournie** [comment]
@cloudyster I forgot to add a second argument here: https://github.com/gtournie/redux-form-validators/blob/master/examples/src/general-validation-form.js#L78
Indeed, `confirmation` needs to access all field values. It's fixed now.
