### ISSUE TITLE
IE 11: SCRIPT1010: Expected identifier

### ISSUE THREAD

**Issue by pachuka** [gtournie/redux-form-validators#33]
Not sure if this is an issue with my build environment
 (typescript transpiled to ES2015), but getting an Expected identifier error in IE11 when it declares the various validators:

```javascript
let absence = Object(__WEBPACK_IMPORTED_MODULE_1__helpers__["e" /* memoize */])(function ({ message, msg, 'if': ifCond, unless }={}) {
  msg = msg || message

  return Object(__WEBPACK_IMPORTED_MODULE_1__helpers__["f" /* prepare */])(ifCond, unless, false, function (value) {
    if ('string' === typeof value ? value.trim() : Object(__WEBPACK_IMPORTED_MODULE_2__file__["c" /* isFileList */])(value) && !isNaN(value.length) ? value.length : value) {
      return __WEBPACK_IMPORTED_MODULE_0__index__["default"].formatMessage(Object(__WEBPACK_IMPORTED_MODULE_1__helpers__["g" /* prepareMsg */])(msg, 'absence'))
    }
  })
})
```

etc.

**Comment by gtournie** [comment]
@pachuka Could you try to run [the example](https://github.com/gtournie/redux-form-validators#example) on IE11 and see if it works please? I don't have IE.

**Comment by pachuka** [comment]
@gtournie , thanks for the quick response. I figured it out just a few minutes ago, don't think its an issue at all with the library. It was an issue with my build environment. In-case anyone runs into this in the future, need to include babel-polyfills and transpile down to ES5 for IE11 to work.

I included the polyfill via webpack

```javascript
entry: {
      app: [
        'babel-polyfill',
        'react-hot-loader/patch',
        'react',
        'react-dom',
        './src/index.web.tsx',
      ]
},
```
