### ISSUE TITLE
Circular dependecies when using the generated lib files.

### ISSUE THREAD

**Issue by LucaMele** [gtournie/redux-form-validators#36]
(!) Circular dependency: node_modules/redux-form-validators/lib/index.js -> node_modules/redux-form-validators/lib/absence.js -> node_modules/redux-form-validators/lib/index.js
(!) Circular dependency: node_modules/redux-form-validators/lib/index.js -> node_modules/redux-form-validators/lib/absence.js -> node_modules/redux-form-validators/lib/helpers.js -> node_modules/redux-form-validators/lib/format.js -> node_modules/redux-form-validators/lib/index.js
(!) Circular dependency: node_modules/redux-form-validators/lib/helpers.js -> node_modules/redux-form-validators/lib/format.js -> node_modules/redux-form-validators/lib/helpers.js
(!) Circular dependency: node_modules/redux-form-validators/lib/index.js -> node_modules/redux-form-validators/lib/absence.js -> node_modules/redux-form-validators/lib/helpers.js -> node_modules/redux-form-validators/lib/format.js -> commonjs-proxy:/Users/lucamele/git/aletheia/node_modules/redux-form-validators/lib/index.js -> node_modules/redux-form-validators/lib/index.js
(!) Circular dependency: node_modules/redux-form-validators/lib/helpers.js -> node_modules/redux-form-validators/lib/format.js -> commonjs-proxy:/Users/lucamele/git/aletheia/node_modules/redux-form-validators/lib/helpers.js -> node_modules/redux-form-validators/lib/helpers.js
(!) Circular dependency: node_modules/redux-form-validators/lib/index.js -> node_modules/redux-form-validators/lib/absence.js -> node_modules/redux-form-validators/lib/helpers.js -> node_modules/redux-form-validators/lib/index.js
(!) Circular dependency: node_modules/redux-form-validators/lib/index.js -> node_modules/redux-form-validators/lib/absence.js -> node_modules/redux-form-validators/lib/file.js -> node_modules/redux-form-validators/lib/index.js
(!) Circular dependency: node_modules/redux-form-validators/lib/index.js -> node_modules/redux-form-validators/lib/acceptance.js -> node_modules/redux-form-validators/lib/index.js
(!) Circular dependency: node_modules/redux-form-validators/lib/index.js -> node_modules/redux-form-validators/lib/add-validator.js -> node_modules/redux-form-validators/lib/index.js
(!) Circular dependency: node_modules/redux-form-validators/lib/index.js -> node_modules/redux-form-validators/lib/confirmation.js -> node_modules/redux-form-validators/lib/index.js
(!) Circular dependency: node_modules/redux-form-validators/lib/index.js -> node_modules/redux-form-validators/lib/date.js -> node_modules/redux-form-validators/lib/index.js
(!) Circular dependency: node_modules/redux-form-validators/lib/index.js -> node_modules/redux-form-validators/lib/inclusion.js -> node_modules/redux-form-validators/lib/index.js
(!) Circular dependency: node_modules/redux-form-validators/lib/index.js -> node_modules/redux-form-validators/lib/length.js -> node_modules/redux-form-validators/lib/index.js
(!) Circular dependency: node_modules/redux-form-validators/lib/index.js -> node_modules/redux-form-validators/lib/numericality.js -> node_modules/redux-form-validators/lib/index.js
(!) Circular dependency: node_modules/redux-form-validators/lib/index.js -> node_modules/redux-form-validators/lib/presence.js -> node_modules/redux-form-validators/lib/index.js
(!) Circular dependency: node_modules/redux-form-validators/lib/index.js -> node_modules/redux-form-validators/lib/url.js -> node_modules/redux-form-validators/lib/index.js

**Comment by LucaMele** [comment]
IMHO this should be avoided and fix asap

**Comment by AndyOGo** [comment]
Just for goods sake:
https://softwareengineering.stackexchange.com/questions/11856/whats-wrong-with-circular-references

**Comment by AndyOGo** [comment]
also a nice read.
https://en.wikipedia.org/wiki/God_object

**Comment by AndyOGo** [comment]
@gtournie 
Any chance you look into this?

For anyone else, we recently published it to npm at [`@axa-ch/redux-form-validators`](https://www.npmjs.com/package/@axa-ch/redux-form-validators).

**Comment by gtournie** [comment]
@AndyOGo This seems like a lot of modifications & refactoring, not sure I'm ok with everything.
@LucaMele Won't be able to fix the circular dependencies until next week. Btw, can you give me a way to reproduce the error please?

**Comment by AndyOGo** [comment]
@gtournie 
Thank you for your answer.
I see, you are right - I made a lot of repeating modifications

**Comment by AndyOGo** [comment]
@gtournie 
BTW.: The are plugins for webpack to check for cyclic dependencies, like [webpack-cyclic-dependency-checker](https://www.npmjs.com/package/webpack-cyclic-dependency-checker)

**Comment by gtournie** [comment]
@AndyOGo I’m in vacations until June 6th. Will look at it when I’m back ;)

**Comment by AndyOGo** [comment]
enjoy your holidays

**Comment by gtournie** [comment]
Fixed

**Comment by AndyOGo** [comment]
hmh, I can't see them being fixed. Or do I miss something 🤔

**Comment by gtournie** [comment]
```
webpack --json --config webpack/development.js > stats.json
iscyclic stats.json
```
=> No cycle detected in redux-form-validators/stats.json
