### ISSUE TITLE
Email validator can not be empty

### ISSUE THREAD

**Issue by lina-salih** [gtournie/redux-form-validators#38]
The RegEx for the email validation does not accept empty string. I think the RegEx should accept also empty string because there is a separate required validator.
 

The RegEx could look like this: /(^$|^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$)/

**Comment by AndyOGo** [comment]
Also the tests are wrong for empty string `''`.
https://github.com/gtournie/redux-form-validators/blob/master/src/__tests__/email.spec.js#L12-L13

**Comment by AndyOGo** [comment]
Same issue exists for `url` validator, can't be empty to.

Also there is a wrong test case:
https://github.com/gtournie/redux-form-validators/blob/master/src/__tests__/url.spec.js#L12-L13

**Comment by gtournie** [comment]
allowBlank is the option you need, indeed. You can set allowBlank globally to true if you want: https://github.com/gtournie/redux-form-validators#default-options
