### ISSUE TITLE
Add code style linters

### ISSUE THREAD

**Issue by AndyOGo** [gtournie/redux-form-validators#39]
- [x] Eslint isn't used
- [x] Editorconfig

**Comment by AndyOGo** [comment]
@gtournie 
Any chance that you can look into this soon too?

**Comment by AndyOGo** [comment]
@gtournie 
Any updates on this?

**Comment by gtournie** [comment]
-> v2.7.1

**Comment by AndyOGo** [comment]
great, though I guess you didn't agree with stuff of my PR 🤔

**Comment by gtournie** [comment]
I didn't want to break the backward-compatibility. Thanks for your help anyway! :)
