### ISSUE TITLE
Demo does not work for birthdays for us older folks

### ISSUE THREAD

**Issue by goldtreefrog** [gtournie/redux-form-validators#43]
In playing with the demo, I noticed that inputting 5/30/55 gave me the error that I must be at least 20 years old. 

Obviously, there are relatively easy ways around this for the programmer-user (including using a 4-character year or a date picker). I was surprised to see such an obvious problem in the demo (for anyone over the age of around 49-1/2 ;-).

Nevertheless, thanks for a great product!

**Comment by gtournie** [comment]
Hey @goldtreefrog, thanks for your feedback. If you choose the 2 digits year, the validator has to guess if you want either 1955 or 2055 and sometimes it doesn't line up with your assumption ([see the rule used internally](https://github.com/gtournie/redux-form-validators/blob/master/src/date.js#L152)).
As I said in the [documentation](https://github.com/gtournie/redux-form-validators#date), it's a very simple validator. Date validation can be much more complex, so if you need something more powerful, feel free to use a date lib and to add your own date validator through the [addValidator](https://github.com/gtournie/redux-form-validators#adding-a-validator) method.
