### ISSUE TITLE
[bug] memoization is not viable, it returns functions with wrong closures

### ISSUE THREAD

**Issue by jedwards1211** [gtournie/redux-form-validators#44]
So someone thought they could be clever and avert the need to declare constant `validator` functions outside of React Elements by memoizing the validator creators.

###  Do not do this, it causes suffering and gnashing of teeth
In general, caching functions passed into your library is *bound* to cause problems, because of **closures**.
Here's how it screwed me over:
```js
export default class PrefixTagsWithFields extends React.Component<PrefixTagsWithFieldsProps> {
  validateCustomPrefix = required({
    // should work, right?
    if: values => get(values, `${this.props.sectionPrefix}.prefixTagsWith`) === CUSTOM_PREFIX,
  })

  render(): React.Node {
    const {classes} = this.props

    return (
        <CustomPrefixField
          className={classes.field}
          validate={this.validateCustomPrefix}
        />
    )
  }
```

I was rendering a `<PrefixTagsWithFields sectionPrefix="one" />` and a `<PrefixTagsWithFields sectionPrefix="two" />`, but when my `if` logic above runs, `this.props.sectionPrefix` is always `one`, which was a real head scratcher.

Finally I dug in the `memoize` function inside `redux-form-validators`.  Here is the cache key for my `required` validator above.  **The cache key is unable to differentiate between the different instances of my component**:
```js
"["if","function _if(values) {\n        return lodash_get__WEBPACK_IMPORTED_MODULE_0___default()(values, _this.props.sectionPrefix + '.prefixTagsWith') === _types_MQTTDevice__WEBPACK_IMPORTED_MODULE_12__[\"CUSTOM_PREFIX\"];\n      }"]"
```
So when `<PrefixTagsWithFields sectionPrefix="two" />` tries to create its validator it gets back one with **the wrong closure**.

**Comment by gtournie** [comment]
@jedwards1211 This is not a redux-form-validators issue. Redux-form has been designed this way (from version 7). There is actually no way to implement a memoize function which could do what you want. If you want more explanations, feel free to reach out the redux-form team

**Comment by jedwards1211** [comment]
You're not getting it - the point is redux-form-validatora should not memoize, period.  At the very least it should give us the option to disable memoization.

**Comment by gtournie** [comment]
Please, read this: https://github.com/erikras/redux-form/issues/3208
There is a reason why redux-form-validators uses memoization. As I told you, redux-form changed its API from version 7 and not using memoization would have resulting in creating a new validation function on every render and would have forced the Field to continuously deregister and re-register.

I get it, you're frustrated and wasted time. But next time, please do some researches before blaming other people/plugins.

**Comment by jedwards1211** [comment]
I know that!  But the proper solution is declaring validators outside of your elements!

```js
const validateField = value => !value || !value.trim() ? 'is required' : null
const Comp = () =>
  <Field validate={validateField} ... />
```

**Comment by jedwards1211** [comment]
@gtournie well if you genuinely want to help the open-source community, why didn't you accept my PR to make redux-form-validators usable in tricky edge cases like this?

I felt pretty frustrated because it seemed like you weren't even considering what I took the time to try to explain, and also that you seemed to think that memoization is the only option for working with redux-form.  

Few project maintainers I have worked with are as dismissive of issues that I took the time to file as you have been here.  And if they do dismiss something, they usually have much more solid reasoning for it.  So I stand by my insults - I expect a more considerate response from project maintainers when I make the effort to try to explain a convoluted problem I'm having!

**Comment by jedwards1211** [comment]
Maybe you would have been more open to my PR had I not had the harsh start-up of "do not do this, it causes suffering" etc?

**Comment by jedwards1211** [comment]
> If you don't like the choices I make you can fork my repo and modify it as much as you want.

In fact I have already done that and I understand. I was mainly frustrated that you blew off my effort to explain the problem and propose a potential solution that would benefit all users of this library.  Is it really in the best interest of users not to provide an option to disable memoization?

**Comment by damonmaria** [comment]
Stepping past the discussion that's gone on above... 

First up, thanks for putting this library out there. Once I found it I threw out my own and took advantage of the advanced features you've built in. 

Here is the redux-form issue capturing the issues with field level validation and the recommended solutions: https://github.com/erikras/redux-form/issues/4017

An issue with memoization using the `toString` of the function (e.g. the `if` option passed to redux-form-validators) is that option "#3" presented by the redux-form team doesn't work as the memo key will still be the same, even if the function belongs to a new component instance. 

If the memoization was left/available to the caller (as it is for field validation in redux-form) then the caller could do their own memoization (e.g. using lodash) with the key based on what they know should cause changes between different instances.

As a concrete example. I'm trying to use the `absense()` validator with an `if` that requires the field has changed. At the moment I can't see how to achieve this as memoization means I can't use a closure:
```typescript
              absence({
                if: (values, value) =>
                  value !== this.props.initialValues.ownerUid &&
                  values.dispenseDeviceId,
                message: 'Can only change owner if device is not deployed',
              }),
```

At least in my case I could get around this if `...args` was also passed to the `if` func, as that would have the `initialValues` in it. 

@gtournie Do you have a suggestion of how to get around this?

**Comment by damonmaria** [comment]
Actually I've just tried out my suggestion above and given the way `memoize` is currently implemented it actually works out of the box. Changing my example above to:
```typescript
              absence({
                if: (values, value) =>
                  value !== this.props.initialValues.ownerUid &&
                  values.dispenseDeviceId,
                memoKey: this.props.initialValues.ownerUid,
                message: 'Can only change owner if device is not deployed',
              }),
```

Works because the `memoize` function is using the entire `options` as the memo key, thus, passing the values used in the closure generates a unique entry. The only issue being is that it breaks in typescript.

**Comment by jedwards1211** [comment]
@damonmaria you're welcome to use my fork that doesn't memoize.  @jcoreio/redux-form-validators

**Comment by gtournie** [comment]
@damonmaria Sorry for the long delay in responding to you. I'm actually working on version 3 which should fix your issues
