### ISSUE TITLE
URL validator passes strings without scheme

### ISSUE THREAD

**Issue by Sminerino** [gtournie/redux-form-validators#46]
"//website.com" is not being recognized as invalid url. Seems like the "?" directly before two slashes ("(https?)**?**\/\/") in url.REG_URL shouldn't be there. Or am I missing something and strings starting with "//" are correct? Example here: https://regex101.com/r/vQ4BNR/1/

**Comment by gtournie** [comment]
Have you tried `url({ protocols: [''] })`? https://github.com/gtournie/redux-form-validators#url

**Comment by Sminerino** [comment]
My problem is not that i need "//website.com" to be valid. I need it to be invalid. But when I use `url()` or `url({protocols: ['http', 'https']})`, this string (starting with "//") counts as correct. What I was asking is: is that intended? 

When using `url({ protocols: [''] })`, both "://x.com" and "//x.com" (with and without colon) are passing validation as correct.
