### ISSUE TITLE
email validation message not working

### ISSUE THREAD

**Issue by maartendraijer** [gtournie/redux-form-validators#5]
When using the `email()` validator the following error will appear in the console:

`[React Intl] Cannot format message: "form.errors.email", using message id as fallback.`

I guess it has something to do with this (unused) variable: https://github.com/gtournie/redux-form-validators/blob/652c095b6092a9fa45b000d3425f7e169310506f/src/email.js#L8. But I'm not sure how to fix.

**Comment by maartendraijer** [comment]
By the way: the same goes for `url()`.

https://github.com/gtournie/redux-form-validators/blob/652c095b6092a9fa45b000d3425f7e169310506f/src/url.js#L8

**Comment by gtournie** [comment]
@maartendraijer I didn't have this issue in the examples. I guess the variable you mentioned could have been removed by your js minifier. It should be fixed now. Please reopen if it's still an issue

**Comment by maartendraijer** [comment]
@gtournie This issue still persists.

My workaround is by copying over https://github.com/gtournie/redux-form-validators/blob/master/examples/src/locales/en.json, `import en from "./locales/en.json";` and then wrapping my main component in a `<IntlProvider locale="en" messages={en}>`.

After that things just work.

**Comment by gtournie** [comment]
@maartendraijer It works perfectly fine when I run the examples.
I'd be happy to reopen if someone tells me how to reproduce it.
