### ISSUE TITLE
`prepare` helper converts NaN to 'NaN', so `required` not working for NaN input value

### ISSUE THREAD

**Issue by sanex3339** [gtournie/redux-form-validators#53]
Hi. I got a problem. I working with typescript and storing empty initial value  with `number` type as `NaN`.
For my field i using `toString` formatter and `toNumber` parser.

So, my value lifecycle looks like:
```
Store -> formatted input -> parsed value
Variant 1) NaN -> '' -> NaN
Variant 2) 1 -> '1' -> 1
```

I noticed, that `prepare` helper converts `NaN` to `'NaN'` string, and after that `required` validator can't properly validate `NaN` value. 

Will happy if you fix it.

**Comment by gtournie** [comment]
Hi. **Input values are always strings**, so valid values are `null` (if input not found), `''` or  something like `'123'`. NaN doesn't fit here. If you do: `input.value = NaN`, the input will convert it to 'NaN'.
`prepare` reproduce this behavior.

In your case you should just initialize it to `null` or `''`.
