### ISSUE TITLE
Cannot start react app after latest changes

### ISSUE THREAD

**Issue by rgnevashev** [gtournie/redux-form-validators#58]
![2019-04-18 21:18:41](https://user-images.githubusercontent.com/123600/56382278-b4e62280-621f-11e9-9b9c-914e3a556d7f.png)
What happened in latest commits? I cannot start a react app anymore..

**Comment by rgnevashev** [comment]
![2019-04-18 21:25:12](https://user-images.githubusercontent.com/123600/56382627-7e5cd780-6220-11e9-9df7-fc46f5b816d4.png)
I dont want install core-js and I would like to support latest 2 version browser and not IE

**Comment by gtournie** [comment]
Fixed in v3.2.1
