### ISSUE TITLE
Any way to remove the react-intl dependency?

### ISSUE THREAD

**Issue by bsears90** [gtournie/redux-form-validators#6]
I'd like to use this library as I love the idea of having these commonly used validation scenarios but don't want to add the complexity involved with react-intl.

**Comment by gtournie** [comment]
What you suggest is to build a internal api to support pluralization and different languages?

react-intl has the big advantage to be built on standards, and to be part of FormatJS.
Plus, I only import the FormattedMessage class, so the complexity should not be that bad ;)

**Comment by bsears90** [comment]
Unless I'm mistaken - the library wont work unless I define an IntlProvider with a locale (and the locale files associated with it). 

My problem is that if I want to use a validation library with redux-form I don't want to go through hoops to get it working, I'd rather have this library be compatible with react-intl instead of dependent on it. 

Possibly integrate it with the redux store as an optional step so you can define a component that the validators return so you can have full control over the formatters (just throwing out ideas)

**Comment by gtournie** [comment]
redux-form-validators 2.0.0 is now dependency-free
