### ISSUE TITLE
redux-form-validators does not work after the initialization of the redux form

### ISSUE THREAD

**Issue by joeyUOFA** [gtournie/redux-form-validators#60]
Hi,

I have explained the code and situation in detail in this thread

https://stackoverflow.com/questions/56401060/redux-form-validators-does-not-work-after-the-initialization-of-the-redux-form

I believe this is an issue related to the redux-form-validators. Can anyone help me check this?

Thanks

**Comment by gtournie** [comment]
Hi,

Seems like your post has been deleted. Do you still have the same issue? Can you describe it briefly here?

**Comment by gtournie** [comment]
I'll reopen this issue if someone can tell me what this is about...

**Comment by anshulsooden** [comment]
@gtournie i think i might be facing the similar issue. 

on Initialising the value in the form(when using redux-form). redux-form-validator does not check/trigger the validation on it own.
Here is my initialisation of redux-form values.

**const mapStateToProps = ({ dialog }) => {
  const { isOpen, dialogTitle, dialogName, requestDetails, action } = dialog;
  let initialValues = {};
  if (requestDetails != null) {
    initialValues = {
      eventId: requestDetails.eventId,
      to: requestDetails.to,
      from: requestDetails.from,
    };
  }
  return {
    initialValues,
    isOpen,
    dialogTitle,
    dialogName,
    requestDetails,
    action
  };
};**

and here is my code where i applied the redux-form-validator "date" in the "from" form-input

**<Field
          name="from"
          label="From"
          styles="col-md-6 mb-3"
          feedbackClass="valid-feedback"
          dateFormat="MM/DD/YYYY"
          validate={[required , date({ format: 'mm/dd/yyyy' }) ]}
          component={RenderDatePicker}
        />**

it suppose to pass/set the validation to true. instead its showing an error for incorrect format. unless i purposely focus the input. only then it changes the validation to true.
